name: Check if for new orders on the website

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Gmail secrets
        run: |
          echo "GMAIL_TOKEN length: ${#GMAIL_TOKEN}"
          echo "GMAIL_REFRESH_TOKEN length: ${#GMAIL_REFRESH_TOKEN}"
          echo "GMAIL_CLIENT_ID length: ${#GMAIL_CLIENT_ID}"
          echo "GMAIL_CLIENT_SECRET length: ${#GMAIL_CLIENT_SECRET}"
          echo "GMAIL_TOKEN_URI: $GMAIL_TOKEN_URI"
        env:
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_TOKEN_URI: ${{ secrets.GMAIL_TOKEN_URI }}

      - name: Run script
        run: python orders_from_website.py
